# Dependabot configuration

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "07:00"
      timezone: "Asia/Jakarta"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "automerge"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
    groups:
      production-deps:
        dependency-type: "production"
        update-types: ["patch", "minor"]
      development-deps:
        dependency-type: "development"
        update-types: ["patch", "minor"]